server:
  port: 8888


spring:
  application:
    name: charles

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/activiti?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 233666

  # 工作流默认配置
  activiti:
    database-schema-update: true
    check-process-definitions: false
    process-definition-location-prefix: classpath:/processes/
# process-definition-location-suffixes:
# - **.bpmn
# - **.bpmn20.xml
    history-level: full
    db-history-used: true

mybatis:
  type-aliases-package: com.charles.blogs.entity
  mapper-locations: classpath:com/charles/blogs/mapper/*.xml

logging:
  level:
    com:
      springboot:
        jwt:
          mapper:
            debug
