server:
  port: 8989


spring:
  application:
    name: jwt

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jwt?characterEncoding=UTF-8
    username: root
    password: 233666
mybatis:
  type-aliases-package: com.springboot.jwt.entity
  mapper-locations: classpath:com/springboot/jwt/mapper/*.xml

logging:
  level:
    com:
      springboot:
        jwt:
          mapper:
            debug
